name: PR Test & Build

on:
  pull_request:
    branches: [main, master]
  push:
    branches: [main, master]

jobs:
  build:
    name: Build Package
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v6.0.2

      - name: Setup Node.js
        uses: actions/setup-node@v6.4.0
        with:
          node-version: "20"
          cache: "yarn"

      - name: Install dependencies
        run: make install

      - name: QA
        run: make qa

      - name: Pack
        run: make pack
