name: Publish ESLint Config

on:
  release:
    types: [created]

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 20

      - run: make install
      - run: make qa
      - run: make publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
